//! Per-user macOS installation. Generated files stay outside the source checkout.
use std::{
    ffi::OsStr,
    fs::{self, OpenOptions},
    io::Write,
    path::{Path, PathBuf},
    process::Stdio,
    time::Duration,
};

use anyhow::{Context, Result, bail};
use clap::ValueEnum;
use futures_util::{SinkExt, StreamExt};
use serde_json::{Value, json};
use tokio::process::Command;
use tokio_tungstenite::tungstenite::Message;

const LABEL: &str = "com.claude-codex.desktop";
const GENERATED: &str = "# Generated by claude-codex-server desktop setup";
const BEGIN: &str = "# BEGIN claude-codex desktop";
const END: &str = "# END claude-codex desktop";

#[derive(Clone, Copy, Debug, ValueEnum)]
pub enum ServiceAction {
    Install,
    Start,
    Stop,
    Restart,
    Status,
    Uninstall,
}

pub struct Installation {
    home: PathBuf,
    root: PathBuf,
    plist: PathBuf,
}

impl Installation {
    pub fn current() -> Result<Self> {
        if !cfg!(target_os = "macos") {
            bail!(
                "Desktop installation requires macOS; other Unix hosts can run app-server --stdio"
            );
        }
        #[cfg(unix)]
        if unsafe { libc::geteuid() } == 0 {
            bail!("Run as your login user, without sudo");
        }
        let home = std::env::var_os("HOME")
            .map(PathBuf::from)
            .context("HOME is not set")?;
        if !home.is_absolute() || !home.is_dir() {
            bail!("HOME must be an existing absolute directory");
        }
        Ok(Self::at_home(home))
    }

    fn at_home(home: PathBuf) -> Self {
        Self {
            root: home.join("Library/Application Support/claude-codex"),
            plist: home.join(format!("Library/LaunchAgents/{LABEL}.plist")),
            home,
        }
    }

    fn socket(&self) -> PathBuf {
        self.root.join("sockets/app-server-control.sock")
    }
    fn domain(&self) -> String {
        format!("gui/{}", unsafe { libc::geteuid() })
    }
    fn job(&self) -> String {
        format!("{}/{LABEL}", self.domain())
    }

    pub async fn install(&self, claude: &Path) -> Result<()> {
        let binary = std::env::current_exe()?.canonicalize()?;
        let claude = resolve_executable(claude)?;
        let codex = genuine_codex()?;
        let plugin_home = std::env::var_os("CLAUDE_CODEX_PLUGIN_HOME")
            .map(PathBuf::from)
            .unwrap_or_else(|| self.home.join(".codex"));
        if !plugin_home.is_absolute() {
            bail!("CLAUDE_CODEX_PLUGIN_HOME must be absolute");
        }
        check_dependencies(&claude, &codex).await?;
        if tokio::time::timeout(
            Duration::from_secs(3),
            tokio::net::TcpStream::connect("127.0.0.1:22"),
        )
        .await
        .ok()
        .and_then(Result::ok)
        .is_none()
        {
            bail!(
                "Enable Remote Login for your user in System Settings > General > Sharing, then rerun install. No system settings were changed."
            );
        }
        let loaded = self.loaded().await?;
        if loaded {
            self.require_idle(false)?;
        }
        self.check_owned_files()?;
        for directory in ["", "bin", "sockets", "codex-home", "state", "logs"] {
            private_directory(&self.root.join(directory))?;
        }
        let key = self.root.join("id_ed25519");
        if fs::symlink_metadata(&key).is_err() {
            run(
                "ssh-keygen",
                &[
                    "-q".into(),
                    "-t".into(),
                    "ed25519".into(),
                    "-N".into(),
                    "".into(),
                    "-C".into(),
                    "claude-codex-desktop".into(),
                    "-f".into(),
                    key.clone().into_os_string(),
                ],
            )
            .await?;
        } else if !fs::symlink_metadata(&key)?.file_type().is_file() {
            bail!("Dedicated SSH identity must be a regular file");
        }
        let public_key = self.root.join("id_ed25519.pub");
        if !public_key.exists() {
            let output = run(
                "ssh-keygen",
                &[
                    "-y".into(),
                    "-P".into(),
                    "".into(),
                    "-f".into(),
                    key.into_os_string(),
                ],
            )
            .await?;
            atomic_write(&public_key, &output, 0o600)?;
        }
        let public = fs::read_to_string(&public_key)?;
        let authorized_line = self.authorized_line(&public)?;
        let username = String::from_utf8(run("id", &["-un".into()]).await?)?;
        let ssh_block = self.ssh_config(username.trim())?;
        let ssh_dir = self.home.join(".ssh");
        if !ssh_dir.exists() {
            private_directory(&ssh_dir)?;
        }
        let config_path = ssh_dir.join("config");
        let authorized_path = ssh_dir.join("authorized_keys");
        // Prepare both edits before changing either user-owned file.
        let config =
            replace_ssh_block(&read_optional(&config_path)?, Some(&ssh_block), &self.root)?;
        let authorized =
            add_authorized_key(&read_optional(&authorized_path)?, &authorized_line, &public)?;
        let known_hosts = self.root.join("known_hosts");
        if read_optional(&known_hosts)?.trim().is_empty() {
            let scanned = run(
                "ssh-keyscan",
                &[
                    "-T".into(),
                    "5".into(),
                    "-t".into(),
                    "ed25519".into(),
                    "localhost".into(),
                ],
            )
            .await?;
            if scanned.is_empty() {
                bail!("Local SSH host key could not be read");
            }
            atomic_write(&known_hosts, &scanned, 0o600)?;
        }
        // Record ownership before copying the executable so an interrupted
        // first install can be retried safely. Ownership checks ran above.
        let metadata = json!({"application":"claude-codex-server","version":env!("CARGO_PKG_VERSION"),"claude":claude,"codex":codex});
        atomic_write(
            &self.root.join("installation.json"),
            &serde_json::to_vec_pretty(&metadata)?,
            0o600,
        )?;
        let installed_binary = self.root.join("bin/claude-codex-server");
        if binary != installed_binary {
            atomic_write(&installed_binary, &fs::read(&binary)?, 0o700)?;
        }
        let environment = self.environment(&claude, &codex, &plugin_home)?;
        let launcher = format!(
            "#!/bin/bash\n{GENERATED}\nset -euo pipefail\n{environment}exec {} --model opus \"$@\"\n",
            shell_quote(&installed_binary)?
        );
        let session = format!(
            "#!/bin/bash\n{GENERATED}\nset -euo pipefail\n{environment}exec /bin/sh -c \"${{SSH_ORIGINAL_COMMAND:?SSH command required}}\"\n"
        );
        atomic_write(&self.root.join("bin/codex"), launcher.as_bytes(), 0o700)?;
        atomic_write(&self.root.join("ssh-session"), session.as_bytes(), 0o700)?;
        atomic_write(&self.root.join("ssh-config"), ssh_block.as_bytes(), 0o600)?;
        atomic_write(
            &self.root.join("authorized-key.txt"),
            authorized_line.as_bytes(),
            0o600,
        )?;
        write_user_file(&config_path, config.as_bytes())?;
        write_user_file(&authorized_path, authorized.as_bytes())?;
        // A changed definition is unloaded and bootstrapped by service install.
        // Only an unchanged, already-loaded definition needs an explicit restart
        // to pick up the new binary and launcher environment.
        let restart = loaded && read_optional(&self.plist)? == self.render_plist()?;
        self.service(ServiceAction::Install, false).await?;
        if restart {
            // install is explicitly an upgrade, but only after the idle check.
            self.service(ServiceAction::Restart, false).await?;
        }
        self.check_ssh().await?;
        println!(
            "Installed. In Codex Settings > Connections, select SSH host claude-codex-local.\nChoose the identity file: {}\nYour normal Codex connection is unchanged.",
            self.root.join("id_ed25519").display()
        );
        Ok(())
    }

    fn check_owned_files(&self) -> Result<()> {
        for path in [self.root.join("bin/codex"), self.root.join("ssh-session")] {
            if path.exists() && !read_optional(&path)?.lines().any(|line| line == GENERATED) {
                bail!("Refusing to replace unrelated file: {}", path.display());
            }
            if fs::symlink_metadata(&path).is_ok_and(|m| m.file_type().is_symlink()) {
                bail!(
                    "Generated installation files must not be symlinks: {}",
                    path.display()
                );
            }
        }
        let installed = self.root.join("bin/claude-codex-server");
        if installed.exists() {
            let metadata = read_optional(&self.root.join("installation.json"))?;
            if serde_json::from_str::<Value>(&metadata)
                .ok()
                .is_none_or(|v| v["application"] != "claude-codex-server")
            {
                bail!(
                    "Refusing to replace unrecognized installed binary: {}",
                    installed.display()
                );
            }
        }
        self.check_plist()
    }

    fn check_plist(&self) -> Result<()> {
        if self.plist.exists()
            && !read_optional(&self.plist)?.contains("Generated by claude-codex-server")
        {
            bail!(
                "Refusing to change unrelated LaunchAgent: {}",
                self.plist.display()
            );
        }
        if fs::symlink_metadata(&self.plist).is_ok_and(|m| m.file_type().is_symlink()) {
            bail!("Generated LaunchAgent must not be a symlink");
        }
        Ok(())
    }

    fn environment(&self, claude: &Path, codex: &Path, plugin_home: &Path) -> Result<String> {
        let values = [
            ("CODEX_HOME", self.root.join("codex-home")),
            ("CODEX_INSTALL_DIR", self.root.join("bin")),
            ("CLAUDE_CODEX_HOME", self.root.join("state")),
            ("CLAUDE_CODEX_SOCKET_DIR", self.root.join("sockets")),
            ("CLAUDE_CODE_EXECUTABLE", claude.to_path_buf()),
            ("CLAUDE_CODEX_PLUGIN_EXECUTABLE", codex.to_path_buf()),
            ("CLAUDE_CODEX_PLUGIN_HOME", plugin_home.to_path_buf()),
        ];
        let mut output = String::new();
        for (name, path) in values {
            output.push_str(&format!("export {name}={}\n", shell_quote(&path)?));
        }
        output.push_str("export CODEX_SSH_SKIP_APP_SERVER_BOOT=true\n");
        Ok(output)
    }

    fn ssh_config(&self, username: &str) -> Result<String> {
        if username.is_empty()
            || !username
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || "_- .".contains(c))
            || username.contains(' ')
        {
            bail!("Unsupported SSH username");
        }
        Ok(format!(
            "Host claude-codex-local\n    HostName localhost\n    User {username}\n    Port 22\n    IdentityFile {}\n    IdentitiesOnly yes\n    IdentityAgent none\n    UserKnownHostsFile {}\n    StrictHostKeyChecking yes\nHost *\n",
            ssh_quote(&self.root.join("id_ed25519"))?,
            ssh_quote(&self.root.join("known_hosts"))?
        ))
    }

    fn authorized_line(&self, public: &str) -> Result<String> {
        let fields: Vec<_> = public.split_whitespace().collect();
        if fields.len() < 2 || fields[0] != "ssh-ed25519" || public.lines().count() != 1 {
            bail!("Dedicated SSH public key is invalid");
        }
        let command = shell_quote(&self.root.join("ssh-session"))?
            .replace('\\', "\\\\")
            .replace('"', "\\\"");
        Ok(format!(
            "from=\"127.0.0.1,::1\",restrict,command=\"{command}\" {}\n",
            public.trim()
        ))
    }

    fn render_plist(&self) -> Result<String> {
        let launcher = xml(&self.root.join("bin/codex"))?;
        let home = xml(&self.home)?;
        let log = xml(&self.root.join("logs/server.log"))?;
        let search_path = format!(
            "{}/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin",
            self.home.display()
        );
        let search_path = xml(Path::new(&search_path))?;
        Ok(format!(
            r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by claude-codex-server desktop setup -->
<plist version="1.0"><dict>
  <key>Label</key><string>{LABEL}</string>
  <key>ProgramArguments</key><array><string>{launcher}</string><string>app-server</string><string>--listen</string><string>unix://</string></array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>ThrottleInterval</key><integer>10</integer>
  <key>ProcessType</key><string>Interactive</string>
  <key>WorkingDirectory</key><string>{home}</string>
  <key>EnvironmentVariables</key><dict><key>PATH</key><string>{search_path}</string></dict>
  <key>StandardOutPath</key><string>{log}</string>
  <key>StandardErrorPath</key><string>{log}</string>
</dict></plist>
"#
        ))
    }

    async fn loaded(&self) -> Result<bool> {
        let output = output("launchctl", &["print".into(), self.job().into()]).await?;
        if output.status.success() {
            return Ok(true);
        }
        let error = String::from_utf8_lossy(&output.stderr);
        if error.contains("Could not find service") || error.contains("could not find service") {
            return Ok(false);
        }
        bail!("Cannot inspect LaunchAgent: {}", error.trim());
    }

    fn require_idle(&self, force: bool) -> Result<()> {
        if force {
            return Ok(());
        }
        let threads = self.root.join("state/threads");
        if !threads.exists() {
            return Ok(());
        }
        for entry in fs::read_dir(threads)? {
            let path = entry?.path();
            if path.extension() != Some(OsStr::new("json")) {
                continue;
            }
            let record: Value = serde_json::from_slice(&fs::read(path)?)?;
            if record["thread"]["status"]["type"] == "active" {
                bail!(
                    "A Claude chat is active. Wait for it to finish; service stop/restart/uninstall --force explicitly interrupts active work."
                );
            }
        }
        Ok(())
    }

    pub async fn service(&self, action: ServiceAction, force: bool) -> Result<()> {
        self.check_plist()?;
        let loaded = self.loaded().await?;
        match action {
            ServiceAction::Status => {
                let ready = self.ready().await.is_ok();
                println!(
                    "Installed: {}\nLoaded: {loaded}\nReady: {ready}\nLog: {}",
                    self.plist.exists(),
                    self.root.join("logs/server.log").display()
                );
            }
            ServiceAction::Install => {
                if !self.root.join("bin/codex").is_file() {
                    bail!("Run claude-codex-server install first");
                }
                private_directory(&self.root.join("logs"))?;
                fs::create_dir_all(self.plist.parent().unwrap())?;
                let plist = self.render_plist()?;
                let previous = read_optional(&self.plist)?;
                if previous != plist {
                    if loaded {
                        self.require_idle(force)?;
                    }
                    // Validate before replacing the running service definition.
                    let candidate = self
                        .plist
                        .with_extension(format!("{}.plist", uuid::Uuid::new_v4()));
                    atomic_write(&candidate, plist.as_bytes(), 0o600)?;
                    let valid = run(
                        "plutil",
                        &["-lint".into(), candidate.clone().into_os_string()],
                    )
                    .await;
                    let _ = fs::remove_file(&candidate);
                    valid?;
                    if loaded {
                        self.bootout().await?;
                    }
                    atomic_write(&self.plist, plist.as_bytes(), 0o600)?;
                    if let Err(error) = self.bootstrap().await {
                        // Restore only this installer-owned definition on bootstrap failure.
                        if !previous.is_empty() {
                            atomic_write(&self.plist, previous.as_bytes(), 0o600)?;
                            if loaded {
                                self.bootstrap()
                                    .await
                                    .context("restore previous LaunchAgent")?;
                            }
                        }
                        return Err(error);
                    }
                } else if !loaded {
                    self.bootstrap().await?;
                }
                self.wait_ready().await?;
                println!("Service installed and ready.");
            }
            ServiceAction::Start => {
                if !self.plist.exists() {
                    bail!("Run claude-codex-server install first");
                }
                if !loaded {
                    self.bootstrap().await?;
                }
                self.wait_ready().await?;
                println!("Service ready.");
            }
            ServiceAction::Stop | ServiceAction::Uninstall => {
                if loaded {
                    self.require_idle(force)?;
                    self.bootout().await?;
                }
                if matches!(action, ServiceAction::Uninstall) && self.plist.exists() {
                    fs::remove_file(&self.plist)?;
                }
                println!("Service stopped. Conversation data and SSH configuration retained.");
            }
            ServiceAction::Restart => {
                if !self.plist.exists() {
                    bail!("Run claude-codex-server install first");
                }
                if loaded {
                    self.require_idle(force)?;
                    self.bootout().await?;
                }
                self.bootstrap().await?;
                self.wait_ready().await?;
                println!("Service restarted and ready.");
            }
        }
        Ok(())
    }

    async fn bootstrap(&self) -> Result<()> {
        // launchd can acknowledge bootout before releasing the old job. A
        // bootstrap immediately afterwards then returns EIO despite a valid
        // plist. Bound retries to that error; other failures remain immediate.
        let deadline = tokio::time::Instant::now() + Duration::from_secs(5);
        loop {
            let result = output(
                "launchctl",
                &[
                    "bootstrap".into(),
                    self.domain().into(),
                    self.plist.clone().into_os_string(),
                ],
            )
            .await?;
            if result.status.success() {
                return Ok(());
            }
            let error = String::from_utf8_lossy(&result.stderr);
            if !error.contains("Bootstrap failed: 5:") || tokio::time::Instant::now() >= deadline {
                bail!("launchctl bootstrap failed: {}", error.trim());
            }
            tokio::time::sleep(Duration::from_millis(250)).await;
        }
    }
    async fn bootout(&self) -> Result<()> {
        run("launchctl", &["bootout".into(), self.job().into()]).await?;
        Ok(())
    }

    async fn ready(&self) -> Result<()> {
        tokio::time::timeout(Duration::from_secs(2), async {
            let stream = tokio::net::UnixStream::connect(self.socket()).await?;
            let (mut websocket, _) = tokio_tungstenite::client_async("ws://codex-app-server/rpc", stream).await?;
            websocket.send(Message::Text(json!({"id":"health","method":"initialize","params":{"clientInfo":{"name":"claude-codex-health","version":"1"}}}).to_string().into())).await?;
            let message = websocket.next().await.context("Service disconnected during health check")??;
            let response: Value = serde_json::from_str(message.to_text()?)?;
            if response["id"] != "health" || !response["result"]["userAgent"].as_str().is_some_and(|agent| agent.contains("claude-codex-server")) {
                bail!("Socket did not answer as claude-codex-server");
            }
            websocket.close(None).await?;
            Ok::<_, anyhow::Error>(())
        }).await.context("Service health check timed out")?
    }

    async fn wait_ready(&self) -> Result<()> {
        let deadline = tokio::time::Instant::now() + Duration::from_secs(20);
        loop {
            match self.ready().await {
                Ok(()) => return Ok(()),
                Err(error) if tokio::time::Instant::now() >= deadline => {
                    bail!(
                        "Service not ready after 20 seconds: {error:#}. Inspect {}. The installed LaunchAgent was retained.",
                        self.root.join("logs/server.log").display()
                    );
                }
                Err(_) => tokio::time::sleep(Duration::from_millis(200)).await,
            }
        }
    }

    async fn check_ssh(&self) -> Result<()> {
        let result = run(
            "ssh",
            &[
                "-F".into(),
                self.root.join("ssh-config").into_os_string(),
                "-oBatchMode=yes".into(),
                "-oConnectTimeout=5".into(),
                "claude-codex-local".into(),
                "\"$CODEX_INSTALL_DIR/codex\" --version".into(),
            ],
        )
        .await?;
        if !String::from_utf8_lossy(&result).contains("claude-codex-server") {
            bail!("SSH connected, but did not select the Claude facade");
        }
        Ok(())
    }

    pub async fn doctor(&self, claude: &Path) -> Result<()> {
        let claude = resolve_executable(claude)?;
        let codex = genuine_codex()?;
        check_dependencies(&claude, &codex).await?;
        println!("Claude and Codex executables: OK");
        self.ready()
            .await
            .context("Service is not ready; run install or service start")?;
        println!("Private service socket: OK");
        self.check_ssh()
            .await
            .context("Local SSH connection failed; check Remote Login and run install again")?;
        println!("Dedicated SSH connection: OK");
        // Use the native status command; never read or print authentication files.
        let status = output(
            claude.as_os_str(),
            &["auth".into(), "status".into(), "--json".into()],
        )
        .await?;
        let native: Value = serde_json::from_slice(&status.stdout)
            .context("Claude auth status did not return JSON")?;
        if !status.status.success() || native["loggedIn"] != true {
            bail!(
                "Claude is not logged in. Run claude auth login in a local terminal, then retry doctor."
            );
        }
        println!("Native Claude authentication: OK (no model request made)");
        Ok(())
    }

    pub async fn uninstall(&self, force: bool) -> Result<()> {
        self.check_owned_files()?;
        let config_path = self.home.join(".ssh/config");
        let original_config = read_optional(&config_path)?;
        let config = replace_ssh_block(&original_config, None, &self.root)?;
        let authorized_path = self.home.join(".ssh/authorized_keys");
        let original_authorized = read_optional(&authorized_path)?;
        let line = read_optional(&self.root.join("authorized-key.txt"))?;
        let authorized = original_authorized
            .lines()
            .filter(|entry| line.trim().is_empty() || *entry != line.trim())
            .collect::<Vec<_>>()
            .join("\n");
        self.service(ServiceAction::Uninstall, force).await?;
        if config != original_config {
            write_user_file(&config_path, config.as_bytes())?;
        }
        if !line.trim().is_empty()
            && original_authorized
                .lines()
                .any(|entry| entry == line.trim())
        {
            write_user_file(&authorized_path, format!("{authorized}\n").as_bytes())?;
        }
        println!(
            "Removed the managed SSH connection and its key authorization. Conversations, identity files and binaries remain in {}.",
            self.root.display()
        );
        Ok(())
    }
}

fn resolve_executable(path: &Path) -> Result<PathBuf> {
    let candidates = if path.components().count() > 1 {
        vec![if path.is_absolute() {
            path.to_path_buf()
        } else {
            std::env::current_dir()?.join(path)
        }]
    } else {
        std::env::split_paths(&std::env::var_os("PATH").unwrap_or_default())
            .map(|dir| dir.join(path))
            .collect()
    };
    for path in candidates {
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            if path.is_absolute()
                && fs::metadata(&path)
                    .is_ok_and(|m| m.is_file() && m.permissions().mode() & 0o111 != 0)
            {
                return Ok(path);
            }
        }
    }
    bail!(
        "Executable not found: {}. Install it or put it on PATH.",
        path.display()
    );
}

fn genuine_codex() -> Result<PathBuf> {
    if let Some(path) = std::env::var_os("CLAUDE_CODEX_PLUGIN_EXECUTABLE") {
        return resolve_executable(Path::new(&path));
    }
    resolve_executable(Path::new("codex")).or_else(|_| {
        resolve_executable(Path::new(
            "/Applications/Codex.app/Contents/Resources/codex",
        ))
    })
}

async fn check_dependencies(claude: &Path, codex: &Path) -> Result<()> {
    let help = run(claude.as_os_str(), &["--help".into()]).await?;
    if !String::from_utf8_lossy(&help).contains("--system-prompt-snapshot") {
        bail!("Update Claude Code: this build requires --system-prompt-snapshot support");
    }
    let version = run(codex.as_os_str(), &["--version".into()]).await?;
    if String::from_utf8_lossy(&version).contains("claude-codex-server") {
        bail!("CLAUDE_CODEX_PLUGIN_EXECUTABLE must point to genuine Codex, not this facade");
    }
    Ok(())
}

async fn output(
    program: impl AsRef<OsStr>,
    args: &[std::ffi::OsString],
) -> Result<std::process::Output> {
    tokio::time::timeout(
        Duration::from_secs(30),
        Command::new(&program)
            .args(args)
            .stdin(Stdio::null())
            .kill_on_drop(true)
            .output(),
    )
    .await
    .with_context(|| format!("{} timed out", program.as_ref().to_string_lossy()))?
    .with_context(|| format!("run {}", program.as_ref().to_string_lossy()))
}

async fn run(program: impl AsRef<OsStr>, args: &[std::ffi::OsString]) -> Result<Vec<u8>> {
    let result = output(&program, args).await?;
    if !result.status.success() {
        bail!(
            "{} failed: {}",
            program.as_ref().to_string_lossy(),
            String::from_utf8_lossy(&result.stderr).trim()
        );
    }
    Ok(result.stdout)
}

fn read_optional(path: &Path) -> Result<String> {
    match fs::read_to_string(path) {
        Ok(value) => Ok(value),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(String::new()),
        Err(error) => Err(error).with_context(|| format!("read {}", path.display())),
    }
}

fn private_directory(path: &Path) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;
    if fs::symlink_metadata(path).is_ok_and(|m| !m.file_type().is_dir()) {
        bail!(
            "Installation directory must not be a symlink or file: {}",
            path.display()
        );
    }
    fs::create_dir_all(path)?;
    fs::set_permissions(path, fs::Permissions::from_mode(0o700))?;
    Ok(())
}

fn atomic_write(path: &Path, bytes: &[u8], mode: u32) -> Result<()> {
    use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};
    let parent = path.parent().context("File requires a parent directory")?;
    let temp = parent.join(format!(".claude-codex-{}.tmp", uuid::Uuid::new_v4()));
    let result = (|| {
        let mut file = OpenOptions::new()
            .write(true)
            .create_new(true)
            .mode(mode)
            .open(&temp)?;
        file.write_all(bytes)?;
        file.set_permissions(fs::Permissions::from_mode(mode))?;
        file.sync_all()?;
        fs::rename(&temp, path)?;
        Ok(())
    })();
    if result.is_err() {
        let _ = fs::remove_file(&temp);
    }
    result
}

fn write_user_file(path: &Path, bytes: &[u8]) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;
    // Preserve dotfiles symlinks by replacing the target, not the link itself.
    let target = if fs::symlink_metadata(path).is_ok() {
        path.canonicalize()?
    } else {
        path.to_path_buf()
    };
    let mode = fs::metadata(&target)
        .map(|m| m.permissions().mode() & 0o777)
        .unwrap_or(0o600);
    atomic_write(&target, bytes, mode)
}

fn checked_path(path: &Path) -> Result<&str> {
    let path = path.to_str().context("Installation paths must be UTF-8")?;
    if path.chars().any(|c| c.is_control()) {
        bail!("Control characters in installation path");
    }
    Ok(path)
}
fn shell_quote(path: &Path) -> Result<String> {
    Ok(format!("'{}'", checked_path(path)?.replace('\'', "'\\''")))
}
fn ssh_quote(path: &Path) -> Result<String> {
    // OpenSSH expands percent tokens even inside quotes.
    Ok(format!(
        "\"{}\"",
        checked_path(path)?
            .replace('%', "%%")
            .replace('\\', "\\\\")
            .replace('"', "\\\"")
    ))
}
fn xml(path: &Path) -> Result<String> {
    Ok(checked_path(path)?
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&apos;"))
}

fn replace_ssh_block(original: &str, block: Option<&str>, root: &Path) -> Result<String> {
    let legacy_include = format!("Include \"{}\"", root.join("ssh-config").display());
    let mut retained = String::new();
    let mut inside = false;
    let mut seen = false;
    for line in original.split_inclusive('\n') {
        match line.trim_end_matches(['\n', '\r']) {
            BEGIN => {
                if inside || seen {
                    bail!("Duplicate managed SSH block; refusing to rewrite configuration");
                }
                inside = true;
                seen = true;
            }
            END => {
                if !inside {
                    bail!("Unmatched managed SSH block terminator");
                }
                inside = false;
            }
            value if !inside && value == legacy_include => {}
            value if !inside => {
                let mut words = value.split_whitespace();
                if block.is_some()
                    && words.next().is_some_and(|w| w.eq_ignore_ascii_case("host"))
                    && words.any(|w| w == "claude-codex-local")
                {
                    bail!(
                        "An unmanaged Host claude-codex-local already exists; choose/remove that entry before installation"
                    );
                }
                retained.push_str(line);
            }
            _ => {}
        }
    }
    if inside {
        bail!("Unclosed managed SSH block; refusing to rewrite configuration");
    }
    match block {
        Some(block) => Ok(format!("{BEGIN}\n{block}{END}\n{retained}")),
        None => Ok(retained),
    }
}

fn add_authorized_key(original: &str, line: &str, public: &str) -> Result<String> {
    if original.lines().any(|existing| existing == line.trim_end()) {
        return Ok(original.to_owned());
    }
    let key = public
        .split_whitespace()
        .nth(1)
        .context("Missing SSH public key")?;
    if original
        .lines()
        .any(|existing| existing.split_whitespace().any(|word| word == key))
    {
        bail!(
            "Dedicated key is already authorized with different restrictions; refusing to broaden or replace it"
        );
    }
    Ok(format!(
        "{original}{}{line}",
        if original.is_empty() || original.ends_with('\n') {
            ""
        } else {
            "\n"
        }
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::os::unix::fs::{PermissionsExt, symlink};

    #[test]
    fn ssh_install_is_idempotent_and_uninstall_preserves_other_hosts() {
        let install = Installation::at_home(PathBuf::from("/Users/example"));
        let original = "# Personal configuration\nHost work\n  HostName example.org\n";
        let block = install.ssh_config("example").unwrap();
        let installed = replace_ssh_block(original, Some(&block), &install.root).unwrap();
        assert_eq!(
            replace_ssh_block(&installed, Some(&block), &install.root).unwrap(),
            installed
        );
        assert_eq!(
            replace_ssh_block(&installed, None, &install.root).unwrap(),
            original
        );
        assert!(
            replace_ssh_block(
                "Host claude-codex-local\n HostName elsewhere\n",
                Some(&block),
                &install.root
            )
            .is_err()
        );
        assert!(replace_ssh_block(BEGIN, Some(&block), &install.root).is_err());
        assert!(replace_ssh_block(END, Some(&block), &install.root).is_err());
    }

    #[test]
    fn ssh_authorization_keeps_existing_keys_and_refuses_weaker_duplicates() {
        let install = Installation::at_home(PathBuf::from("/Users/example"));
        let public = "ssh-ed25519 TEST_PUBLIC_KEY fixture\n";
        let line = install.authorized_line(public).unwrap();
        let original = "ssh-ed25519 OTHER_PUBLIC_KEY user";
        let installed = add_authorized_key(original, &line, public).unwrap();
        assert!(installed.starts_with(original));
        assert_eq!(
            add_authorized_key(&installed, &line, public).unwrap(),
            installed
        );
        assert!(add_authorized_key(public, &line, public).is_err());
        assert!(
            install
                .authorized_line("ssh-ed25519 KEY\nssh-ed25519 EXTRA")
                .is_err()
        );
    }

    #[test]
    fn file_updates_preserve_dotfiles_symlinks_and_permissions() {
        let temp = tempfile::tempdir().unwrap();
        let target = temp.path().join("dotfiles-config");
        let link = temp.path().join("config");
        fs::write(&target, "old").unwrap();
        fs::set_permissions(&target, fs::Permissions::from_mode(0o640)).unwrap();
        symlink(&target, &link).unwrap();
        write_user_file(&link, b"updated").unwrap();
        assert!(link.symlink_metadata().unwrap().file_type().is_symlink());
        assert_eq!(fs::read_to_string(target).unwrap(), "updated");
        assert_eq!(
            fs::metadata(link).unwrap().permissions().mode() & 0o777,
            0o640
        );
        let new = temp.path().join("private");
        write_user_file(&new, b"private").unwrap();
        assert_eq!(
            fs::metadata(new).unwrap().permissions().mode() & 0o777,
            0o600
        );
    }

    #[test]
    fn installation_refuses_unmanaged_files_and_linked_directories() {
        let temp = tempfile::tempdir().unwrap();
        let install = Installation::at_home(temp.path().to_path_buf());
        private_directory(&install.root.join("bin")).unwrap();
        fs::write(install.root.join("bin/codex"), "user script").unwrap();
        assert!(install.check_owned_files().is_err());
        assert_eq!(
            fs::read_to_string(install.root.join("bin/codex")).unwrap(),
            "user script"
        );
        let link = temp.path().join("linked");
        symlink(&install.root, &link).unwrap();
        assert!(private_directory(&link).is_err());
    }

    #[test]
    fn active_conversations_require_explicit_force() {
        let temp = tempfile::tempdir().unwrap();
        let install = Installation::at_home(temp.path().to_path_buf());
        let threads = install.root.join("state/threads");
        fs::create_dir_all(&threads).unwrap();
        let record = threads.join("fixture.json");
        fs::write(&record, r#"{"thread":{"status":{"type":"active"}}}"#).unwrap();
        assert!(install.require_idle(false).is_err());
        install.require_idle(true).unwrap();
        fs::write(&record, r#"{"thread":{"status":{"type":"idle"}}}"#).unwrap();
        install.require_idle(false).unwrap();
    }

    #[test]
    fn shell_paths_are_data_not_commands() {
        let value = Path::new("/tmp/spaces 'quotes' $(printf unsafe) `printf unsafe` & <test>");
        let quoted = shell_quote(value).unwrap();
        let result = std::process::Command::new("/bin/sh")
            .arg("-c")
            .arg(format!("printf %s {quoted}"))
            .output()
            .unwrap();
        assert!(result.status.success());
        assert_eq!(
            String::from_utf8(result.stdout).unwrap(),
            value.to_str().unwrap()
        );
        assert!(shell_quote(Path::new("/tmp/new\nline")).is_err());
    }

    #[cfg(target_os = "macos")]
    #[test]
    fn generated_plist_and_ssh_config_parse_with_native_tools() {
        let temp = tempfile::tempdir().unwrap();
        let install = Installation::at_home(temp.path().join("space & 'quote'"));
        let plist = temp.path().join("service.plist");
        fs::write(&plist, install.render_plist().unwrap()).unwrap();
        assert!(
            std::process::Command::new("plutil")
                .arg("-lint")
                .arg(plist)
                .output()
                .unwrap()
                .status
                .success()
        );
        let config = temp.path().join("ssh-config");
        fs::write(&config, install.ssh_config("example").unwrap()).unwrap();
        let result = std::process::Command::new("ssh")
            .args(["-G", "-F"])
            .arg(config)
            .arg("claude-codex-local")
            .output()
            .unwrap();
        assert!(
            result.status.success(),
            "{}",
            String::from_utf8_lossy(&result.stderr)
        );
        let resolved = String::from_utf8(result.stdout).unwrap();
        assert!(resolved.contains("hostname localhost\n"));
        assert!(resolved.contains("identitiesonly yes\n"));
        assert!(resolved.contains(&format!(
            "identityfile {}\n",
            install.root.join("id_ed25519").display()
        )));
    }
}
