//! The vendored schema is generated by `codex-cli 0.160.0`, including experimental APIs.
//! Codex uses JSON-RPC semantics but omits the `jsonrpc` member on the wire.
use std::{
    sync::OnceLock,
    time::{SystemTime, UNIX_EPOCH},
};

use serde_json::{Value, json};

pub const VERSION: &str = env!("CARGO_PKG_VERSION");
pub const CODEX_VERSION: &str = "0.160.0";
pub const SCHEMA: &str = include_str!("../protocol/codex-0.160.0.json");
pub const SUPPORTED_METHODS: &[&str] = &[
    "skills/list",
    "skills/extraRoots/set",
    "hooks/list",
    "plugin/reconcile",
    "plugin/skill/read",
    "plugin/share/save",
    "plugin/share/updateTargets",
    "plugin/share/list",
    "plugin/share/checkout",
    "plugin/share/delete",
    "skills/config/write",
    "mcpServer/oauth/login",
    "mcpServerStatus/list",
    "mcpServer/resource/read",
    "mcpServer/event/stream/start",
    "mcpServer/event/stream/stop",
    "mcpServer/tool/call",
    "config/value/write",
    "initialize",
    "thread/start",
    "thread/resume",
    "thread/fork",
    "thread/revert",
    "thread/rollback",
    "thread/attachment/add",
    "thread/attachment/list",
    "thread/attachment/remove",
    "plugin/list",
    "plugin/installed",
    "plugin/search",
    "plugin/read",
    "plugin/install",
    "plugin/uninstall",
    "thread/read",
    "thread/list",
    "thread/loaded/list",
    "thread/turns/list",
    "thread/items/list",
    "thread/timeline/list",
    "thread/name/set",
    "thread/archive",
    "thread/unarchive",
    "thread/unsubscribe",
    "turn/start",
    "turn/interrupt",
    "turn/steer",
    "thread/queue/add",
    "thread/queue/list",
    "thread/queue/update",
    "thread/queue/delete",
    "thread/queue/reorder",
    "thread/queue/start",
    "model/list",
    "account/read",
    "getAuthStatus",
    "config/read",
    "config/batchWrite",
    "fs/createDirectory",
    "fs/getMetadata",
    "fs/readDirectory",
    "fs/readFile",
    "fs/writeFile",
    "fs/copy",
    "fs/remove",
    "command/exec",
    "command/exec/write",
    "command/exec/resize",
    "command/exec/terminate",
    "process/spawn",
    "process/writeStdin",
    "process/kill",
    "process/resizePty",
    "configRequirements/read",
    "collaborationMode/list",
    "experimentalFeature/list",
];

#[derive(Debug, Clone)]
pub struct RpcError {
    pub code: i32,
    pub message: String,
    pub data: Option<Value>,
}

impl RpcError {
    pub fn new(code: i32, message: impl Into<String>) -> Self {
        Self {
            code,
            message: message.into(),
            data: None,
        }
    }
    pub fn invalid(message: impl Into<String>) -> Self {
        Self::new(-32602, message)
    }
    pub fn internal(error: impl std::fmt::Display) -> Self {
        Self::new(-32603, error.to_string())
    }
    pub fn unsupported(method: &str) -> Self {
        Self {
            code: -32601,
            message: format!("Method not supported by Claude facade: {method}"),
            data: Some(
                json!({"supportedMethods": SUPPORTED_METHODS, "protocolVersion": CODEX_VERSION}),
            ),
        }
    }
    pub fn response(&self, id: Value) -> Value {
        let mut error = json!({"code": self.code, "message": self.message});
        if let Some(data) = &self.data {
            error["data"] = data.clone();
        }
        json!({"id": id, "error": error})
    }
}
impl std::fmt::Display for RpcError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.message)
    }
}
impl std::error::Error for RpcError {}
pub type RpcResult<T> = Result<T, RpcError>;

pub fn now_ms() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis() as u64
}
pub fn now() -> u64 {
    now_ms() / 1000
}
pub fn id() -> String {
    uuid::Uuid::now_v7().to_string()
}
pub fn response(id: Value, result: Value) -> Value {
    json!({"id": id, "result": result})
}
pub fn notification(method: &str, params: Value) -> Value {
    json!({"method": method, "params": params})
}
pub fn required_str<'a>(value: &'a Value, field: &str) -> RpcResult<&'a str> {
    value[field]
        .as_str()
        .filter(|s| !s.is_empty())
        .ok_or_else(|| RpcError::invalid(format!("{field} must be a nonempty string")))
}

/// Reject semantics we cannot implement; accepting and silently ignoring a setting is not compatibility.
pub fn supported_fields(params: &Value, supported: &[&str]) -> RpcResult<()> {
    let object = params
        .as_object()
        .ok_or_else(|| RpcError::invalid("params must be an object"))?;
    let unsupported: Vec<_> = object
        .iter()
        .filter(|(key, value)| !value.is_null() && !supported.contains(&key.as_str()))
        .map(|(key, _)| key.as_str())
        .collect();
    if !unsupported.is_empty() {
        return Err(RpcError::invalid(format!(
            "Unsupported parameters: {}",
            unsupported.join(", ")
        )));
    }
    Ok(())
}

pub struct Schemas {
    requests: jsonschema::Validator,
}
impl Schemas {
    pub fn get() -> &'static Self {
        static INSTANCE: OnceLock<Schemas> = OnceLock::new();
        INSTANCE.get_or_init(|| {
            let mut root: Value = serde_json::from_str(SCHEMA).expect("vendored protocol schema");
            let mut schema = root["definitions"]["ClientRequest"].clone();
            schema["oneOf"].as_array_mut().unwrap().retain(|request| {
                request["properties"]["method"]["enum"][0]
                    .as_str()
                    .is_some_and(|name| SUPPORTED_METHODS.contains(&name))
            });
            // The schema export omits this legacy RPC, but desktop still calls
            // it. Shape matches app-server-protocol's v1 GetAuthStatusParams.
            schema["oneOf"].as_array_mut().unwrap().push(json!({
                "type": "object", "required": ["id", "method", "params"],
                "properties": {
                    "id": {"type": ["string", "integer"]},
                    "method": {"const": "getAuthStatus"},
                    "params": {"type": "object", "properties": {
                        "includeToken": {"type": ["boolean", "null"]},
                        "refreshToken": {"type": ["boolean", "null"]}
                    }, "additionalProperties": false}
                }
            }));
            schema["oneOf"].as_array_mut().unwrap().push(json!({
                "type":"object","required":["id","method","params"],
                "properties": {
                    "id":{"type":["string","integer"]}, "method":{"const":"thread/rollback"},
                    "params":{"type":"object","required":["threadId","numTurns"],"additionalProperties":false,
                        "properties":{"threadId":{"type":"string","minLength":1},"numTurns":{"type":"integer","minimum":1,"maximum":4294967295u64}}}
                }
            }));
            // Compile shared definitions once, rather than cloning and compiling
            // the entire protocol for every supported method at process startup.
            schema["definitions"] = root["definitions"].take();
            let requests = jsonschema::validator_for(&schema).expect("valid request schema");
            Self { requests }
        })
    }
    pub fn validate(&self, method: &str, request: &Value) -> RpcResult<()> {
        if !SUPPORTED_METHODS.contains(&method) {
            return Err(RpcError::unsupported(method));
        }
        if let Some(error) = self.requests.iter_errors(request).next() {
            // Do not echo user content in an error, only the invalid field location.
            return Err(RpcError::invalid(format!(
                "Invalid {method} request at {} ({})",
                error.instance_path, error.schema_path
            )));
        }
        Ok(())
    }
}

pub fn new_turn(turn_id: &str) -> Value {
    json!({"id": turn_id, "items": [], "itemsView": "full", "status": "inProgress",
        "error": null, "startedAt": now(), "completedAt": null, "durationMs": null})
}

pub fn usage(input: u64, cached: u64, cache_write: u64, output: u64) -> Value {
    json!({"totalTokens": input + cached + cache_write + output,
        "inputTokens": input + cached + cache_write, "cachedInputTokens": cached,
        "cacheWriteInputTokens": cache_write, "outputTokens": output, "reasoningOutputTokens": 0})
}

pub fn model_entry(model: &str, is_default: bool) -> Value {
    json!({"id": model, "model": model, "displayName": model, "description": "Custom Claude model identifier",
        "upgrade": null, "upgradeInfo": null, "availabilityNux": null, "modelSpecialty": null,
        "hidden": false, "supportedReasoningEfforts": [],
        "defaultReasoningEffort": "none", "inputModalities": ["text", "image"],
        "supportsPersonality": false, "multiAgentVersion": null, "additionalSpeedTiers": [],
        "serviceTiers": [], "defaultServiceTier": null, "availableAccessPrograms": null, "isDefault": is_default})
}

/// Preserve the native CLI's model names and per-model effort capabilities.
pub fn claude_model_entry(model: &Value, default: &str) -> RpcResult<Value> {
    let name = required_str(model, "value")?;
    let mut entry = model_entry(name, name == default);
    entry["displayName"] = json!(required_str(model, "displayName")?);
    entry["description"] = model["description"].as_str().unwrap_or("").into();
    let efforts: Vec<_> = model["supportedEffortLevels"]
        .as_array()
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .filter(|e| ["low", "medium", "high", "xhigh", "max"].contains(e))
        .map(|e| json!({"reasoningEffort": e, "description": e}))
        .collect();
    entry["defaultReasoningEffort"] = if efforts.iter().any(|e| e["reasoningEffort"] == "high") {
        json!("high")
    } else {
        efforts
            .first()
            .map(|e| e["reasoningEffort"].clone())
            .unwrap_or(json!("none"))
    };
    entry["supportedReasoningEfforts"] = if efforts.is_empty() {
        json!([{"reasoningEffort":"none", "description":"Model default"}])
    } else {
        json!(efforts)
    };
    Ok(entry)
}
